namespace:
  name: prod
  count: 5

 
image:
  imagePullPolicy: Always


resources:
  requestsMemory: "128Mi"
  requestsCPU: "350m"
  limitsMemory: "256Mi"
  limitsCPU: "500m"

livenessProbe:
  port: 3111

readnessProbe:
  port: 3111


replicaCount: 5
port: 7111
protocol: TCP
