namespace:
  name: sandbox
  count: 1

 
image:
  repository: lepirescomp/techtrends 
  tag: latest
  imagePullPolicy: IfNotPresent


livenessProbe:
  path: /healthz
  port: 3111

readnessProbe:
  path: /healthz
  port: 3111


resources:
  requestsMemory: "64Mi"
  requestsCPU: "250m"
  limitsMemory: "128Mi"
  limitsCPU: "500m"


replicaCount: 1
port: 4111
protocol: TCP
targetPort: 3111
clusterIP: ClusterIP